ALTER TABLE "User" ADD COLUMN "profileScore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "onboardingStep" TEXT NOT NULL DEFAULT 'basics';
ALTER TABLE "User" ADD COLUMN "onboardingCompleted" BOOLEAN NOT NULL DEFAULT false;
